import AppProvider from '@/components/wrappers/AppProvider';
import ReactQueryProvider from '@/components/wrappers/ReactQueryProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import UILayout from '../components/wrappers/UILayout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <AntdRegistry>
            <AppProvider>
              <UILayout>{children}</UILayout>
            </AppProvider>
          </AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;

